FROM python:3.8-alpine

# CREDITS
LABEL maintainer="Clement LE GRUIEC <clement.le-gruiec@imt-atlantique.net>"
LABEL version="1.0"

# INSTALL tshark
RUN apk add tshark

# COPY FILES
RUN mkdir /app
COPY requirements.txt /app
COPY ./sniffer/pandore_* /app

# INSTALL LIBRARIES
WORKDIR /app
RUN pip install --user -r requirements.txt

CMD ["python3", "/app/pandore_agent.py"]

# docker run --rm -it  --cap-add=NET_RAW --cap-add=NET_ADMIN --net=host pandorenetwork