FROM python:3.8-alpine

# CREDITS
LABEL maintainer="Clement LE GRUIEC <clement.le-gruiec@imt-atlantique.net>"
LABEL version="1.0"

# INSTALL tshark
RUN apk add tshark

# COPY FILES
RUN mkdir /application
ADD requirements.txt /application
ADD application /application/



# INSTALL LIBRARIES
WORKDIR /application
RUN pip install --user -r requirements.txt

#TimeZone

ENV TZ=Europe/Paris 
RUN apk add --no-cache tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# DEFAULT PORT
EXPOSE 5555

# RUN

ENTRYPOINT [ "python" ]
CMD ["/application/pandore_agent.py"]

# docker run --rm -it  --cap-add=NET_RAW --cap-add=NET_ADMIN --net=host pandorenetwork
